default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: db
  username: postgres
  # password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: todo_application_development

test:
  <<: *default
  database: todo_application_test

production:
  <<: *default
  database: <%= ENV["DB_DATABASE"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOSTNAME"] %>
  port: <%= ENV["DB_PORT"] %>
